import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, BookOpen, CheckCircle2, ChevronRight, CircleDollarSign, CloudRain, Lock, Plus, ShoppingBag, Sparkles, Target, Trash2, UserRound } from 'lucide-react';
import cityArt from './assets/night-district.svg';
import boardArt from './assets/case-board.svg';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000';
type Character = { id:number; level:number; xp:number; xp_to_next_level:number; resource_meter:number; gold:number; day_index:number; stats:Record<string,number> };
type Quest = { id:number; title:string; category:string; difficulty:string; is_completed:boolean; xp_reward:number; gold_reward:number; resource_reward:number };
type Item = { id:number; name:string; cost:number; description:string };
type Inventory = { id:number; shop_item_id:number; name:string; description:string };
const categories = ['Gym/Sports/Chores', 'Coding/Study', 'Reading/Reflection', 'Sleep/Health/Self-care'];
const difficulties = ['Easy', 'Medium', 'Hard'];
const token = () => localStorage.getItem('wayfarer-token');

async function api(path:string, options:RequestInit = {}) {
  const response = await fetch(API + path, { ...options, headers: { 'Content-Type':'application/json', ...(token() ? { Authorization:`Bearer ${token()}` } : {}), ...options.headers } });
  if (!response.ok) throw new Error((await response.json().catch(() => ({ detail:'The line to the station went quiet.' }))).detail);
  return response.status === 204 ? null : response.json();
}

function Auth({ onToken }:{ onToken:() => void }) {
  const [signup, setSignup] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event:React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const result = await api(`/auth/${signup ? 'signup' : 'login'}`, { method:'POST', body:JSON.stringify({ email, password }) }); localStorage.setItem('wayfarer-token', result.access_token); onToken(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  return <main className="arrival"><img className="arrival-art" src={cityArt} alt="Illustrated rain-soaked city district"/><div className="arrival-shade"/><header className="landing-nav"><div className="wordmark"><span>W</span> WAYFARER</div><p>AN INVESTIGATIVE LIFE RPG</p></header><section className="arrival-copy"><p className="kicker">CASE FILE 001 <i/> THE MISSING CHIEF</p><h1>Live the case.<br/><em>Find yourself.</em></h1><p className="lead">Turn real-world momentum into evidence. Every quest recovers another piece of a town built to make you forget.</p><div className="landing-tags"><span>7 NIGHTS</span><span>1 LOST MEMORY</span><span>YOUR CHOICES MATTER</span></div></section><form onSubmit={submit} className="auth"><p className="form-kicker">{signup ? 'OPEN A NEW CASE' : 'RETURN TO THE STATION'}</p><h2>{signup ? 'Start your file.' : 'Welcome back, Chief.'}</h2><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" minLength={8} value={password} onChange={event => setPassword(event.target.value)} placeholder="At least 8 characters" required/></label>{error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Checking the files…' : signup ? <>Open the file <ArrowRight/></> : <>Enter the station <ArrowRight/></>}</button><button type="button" className="switch" onClick={() => setSignup(!signup)}>{signup ? 'Already have a file? Sign in' : 'New here? Create an account'}</button></form><p className="scroll-hint">SCROLL TO INVESTIGATE <ChevronRight/></p></main>;
}

function Bar({ name, value, max, color = 'rose' }:{ name:string; value:number; max:number; color?:string }) { return <div className="bar"><div><span>{name}</span><b>{value}{max !== 100 && ` / ${max}`}</b></div><div className="track"><i className={color} style={{ width:`${Math.min(100, value / max * 100)}%` }}/></div></div>; }

function App() {
  const [ready, setReady] = useState(!!token()); const [character, setCharacter] = useState<Character|null>(null); const [quests, setQuests] = useState<Quest[]>([]); const [items, setItems] = useState<Item[]>([]); const [inventory, setInventory] = useState<Inventory[]>([]); const [screen, setScreen] = useState<'town'|'quests'|'story'|'shop'>('town'); const [story, setStory] = useState<any>(null); const [meta, setMeta] = useState({ demo_mode:false }); const [toast, setToast] = useState(''); const [loading, setLoading] = useState(true);
  const say = (message:string) => { setToast(message); window.setTimeout(() => setToast(''), 3500); };
  const load = async () => { try { const [c, q, i, inv, m] = await Promise.all([api('/character/me'), api('/quests'), api('/shop/items'), api('/inventory/me'), api('/meta')]); setCharacter(c); setQuests(q); setItems(i); setInventory(inv); setMeta(m); } catch (err) { say((err as Error).message); if ((err as Error).message.includes('token')) { localStorage.removeItem('wayfarer-token'); setReady(false); } } finally { setLoading(false); } };
  useEffect(() => { if (ready) load(); }, [ready]);
  useEffect(() => { if (ready && screen === 'story' && character) api(`/story/day/${character.day_index}`).then(setStory).catch(err => say(err.message)); }, [ready, screen, character?.day_index]);
  if (!ready) return <Auth onToken={() => { setReady(true); setLoading(true); }}/>;
  if (loading || !character) return <main className="loading-screen"><img src={cityArt} alt=""/><p>THE CITY IS LOADING YOUR FILE…</p></main>;
  const completed = quests.filter(quest => quest.is_completed).length;
  async function complete(quest:Quest) { setQuests(list => list.map(current => current.id === quest.id ? { ...current, is_completed:true } : current)); try { const result = await api(`/quests/${quest.id}/complete`, { method:'PATCH' }); setCharacter(result.character); setQuests(list => list.map(current => current.id === quest.id ? result.quest : current)); say(`Case closed. +${quest.xp_reward} XP, +${quest.gold_reward} gold.`); } catch (err) { setQuests(list => list.map(current => current.id === quest.id ? quest : current)); say((err as Error).message); } }
  async function advance() { try { const result = await api('/dev/advance-day', { method:'POST' }); setCharacter(result.character); say(result.advanced ? 'Night falls. A new file opens.' : 'Dawn has already come.'); } catch (err) { say((err as Error).message); } }
  const navigation:[typeof screen, string][] = [['town','Command Center'], ['quests','Case Board'], ['story','Case Files'], ['shop','Field Kit']];
  return <main className="app-shell"><div className="app-glow"/><header className="app-header"><button className="wordmark home" onClick={() => setScreen('town')}><span>W</span> WAYFARER</button><nav aria-label="Primary">{navigation.map(([key, label], index) => <button key={key} className={screen === key ? 'active' : ''} onClick={() => setScreen(key)}><small>0{index + 1}</small>{label}</button>)}</nav><button className="profile-chip" onClick={() => { localStorage.removeItem('wayfarer-token'); setReady(false); }}><UserRound/> Chief Rook <span>Sign out</span></button></header><section className="layout"><aside className="profile-panel"><div className="portrait"><div className="portrait-ring"><UserRound/></div><span>CHIEF</span></div><h2>Rook</h2><p className="rank">LEVEL {character.level} <i/> NIGHT {character.day_index}</p><Bar name="CASE EXPERIENCE" value={character.xp} max={character.xp_to_next_level}/><Bar name="CLARITY" value={character.resource_meter} max={100} color="cyan"/><div className="gold"><CircleDollarSign/> <b>{character.gold}</b> <span>GOLD</span></div><div className="stat-list">{Object.entries(character.stats).map(([name, value]) => <Bar key={name} name={name.toUpperCase()} value={value} max={100}/>)}</div><div className="side-quote">“The town has a long memory. Yours is the only one missing.”</div></aside><section className="content"><AnimatePresence mode="wait"><motion.div key={screen} initial={{ opacity:0, y:12 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:-8 }} transition={{ duration:.28 }}>{screen === 'town' && <Town char={character} completed={completed} onBoard={() => setScreen('quests')}/>} {screen === 'quests' && <Board quests={quests} onComplete={complete} reload={load} say={say}/>} {screen === 'story' && <Story story={story} char={character}/>} {screen === 'shop' && <Shop items={items} inventory={inventory} char={character} buy={async id => { try { const result = await api(`/shop/purchase/${id}`, { method:'POST' }); setCharacter(result.character); setInventory(result.inventory); say('Relic secured in the evidence locker.'); } catch (err) { say((err as Error).message); } }}/>}</motion.div></AnimatePresence></section></section>{meta.demo_mode && <button className="sleep" onClick={advance}>End shift <ArrowRight/></button>}<AnimatePresence>{toast && <motion.div initial={{ opacity:0, y:16 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:16 }} className="toast" role="status">{toast}</motion.div>}</AnimatePresence></main>;
}

function Town({ char, completed, onBoard }:{ char:Character; completed:number; onBoard:() => void }) { const untilNext = Math.max(0, 2 - (completed % 2 || 2)); return <><section className="district-hero"><img src={cityArt} alt="Illustrated skyline of the rain-soaked district"/><div className="district-copy"><p className="kicker">NIGHT {char.day_index} / THE BELL & ASH DISTRICT</p><h1>The truth is <em>out there.</em></h1><p>Complete real cases. Rebuild a life. Find out why the city decided to forget its Chief.</p><button className="primary" onClick={onBoard}>Take a case <ArrowRight/></button></div><div className="hero-status"><span>LIVE CASE</span><b>{completed}</b><small>CASES CLOSED TODAY</small></div></section><section className="dashboard-grid"><article className="progress-card"><p className="kicker">ACTIVE INVESTIGATION</p><h2>Pieces of the <em>past.</em></h2><div className="progress-number"><b>{completed.toString().padStart(2,'0')}</b><span>/ 10<br/>CASES</span></div><div className="wide-track"><i style={{ width:`${Math.min(100, completed * 10)}%` }}/></div><p>{untilNext ? `${untilNext} more case${untilNext === 1 ? '' : 's'} until the next fragment.` : 'Your next completed case unlocks new evidence.'}</p></article><article className="board-visual"><img src={boardArt} alt="Illustrated evidence board with connected case notes"/><div><Target/><p>NEW LEADS<br/><b>WAITING AT THE BOARD</b></p></div></article></section></>; }

function Board({ quests, onComplete, reload, say }:{ quests:Quest[]; onComplete:(quest:Quest) => void; reload:() => void; say:(message:string) => void }) { const [title, setTitle] = useState(''); const [category, setCategory] = useState(categories[0]); const [difficulty, setDifficulty] = useState('Easy'); async function add(event:React.FormEvent) { event.preventDefault(); try { await api('/quests', { method:'POST', body:JSON.stringify({ title, category, difficulty }) }); setTitle(''); reload(); } catch (err) { say((err as Error).message); } } return <><section className="section-heading"><p className="kicker">YOUR OPEN INVESTIGATIONS</p><h1>The case <em>board.</em></h1><p>No detours. No fillers. Turn the work you need to do into evidence that moves the story forward.</p></section><form className="quest-form" onSubmit={add}><input aria-label="Quest title" placeholder="What needs to get done?" value={title} onChange={event => setTitle(event.target.value)} required/><select value={category} onChange={event => setCategory(event.target.value)}>{categories.map(name => <option key={name}>{name}</option>)}</select><select value={difficulty} onChange={event => setDifficulty(event.target.value)}>{difficulties.map(name => <option key={name}>{name}</option>)}</select><button className="primary"><Plus/> Add case</button></form><div className="quest-list">{quests.length === 0 ? <div className="empty-state"><Sparkles/><h2>No loose ends. Yet.</h2><p>Start with one small action. The board is always listening.</p></div> : quests.map(quest => <article className={'quest '+(quest.is_completed ? 'done' : '')} key={quest.id}><button className="complete" aria-label={`Complete ${quest.title}`} disabled={quest.is_completed} onClick={() => onComplete(quest)}><CheckCircle2/></button><div className="quest-main"><p className="case-number">CASE #{String(quest.id).padStart(3, '0')}</p><h2>{quest.title}</h2><div><span>{quest.category}</span><span className={'difficulty '+quest.difficulty.toLowerCase()}>{quest.difficulty}</span></div></div><div className="rewards"><b>+{quest.xp_reward} XP</b><span>+{quest.gold_reward} GOLD</span></div><button className="delete" onClick={async () => { await api(`/quests/${quest.id}`, { method:'DELETE' }); reload(); }} aria-label={`Delete ${quest.title}`}><Trash2/></button></article>)}</div></>; }

function Story({ story, char }:{ story:any; char:Character }) { if (!story) return <div className="loading-story">UNSEALING THE CASE FILE…</div>; return <><section className="section-heading story-heading"><p className="kicker">RECOVERED FILE / NIGHT {char.day_index}</p><h1>{story.title}</h1><p>{story.setup}</p></section><div className="story-rail">{story.fragments?.map((fragment:any, index:number) => <article className={'fragment '+(fragment.variant === 'hard' ? 'hard' : '')} key={fragment.index}><span>{String(index + 1).padStart(2,'0')}</span><p>{fragment.text}</p></article>)}{story.reveal && <article className={'reveal '+(story.reveal.variant === 'hard' ? 'hard' : '')}><p className="kicker">END-OF-NIGHT REVELATION</p><h2>{story.reveal.text}</h2></article>}{story.finale && <article className="reveal"><p className="kicker">YOUR FINAL RECORD</p><h2>{story.finale}</h2></article>}{story.fragments?.length === 0 && <div className="empty-state"><Lock/><h2>This file is still sealed.</h2><p>Close two cases to recover your first fragment.</p></div>}</div><div className="future">{Array.from({ length:7 - char.day_index }, (_, index) => <div key={index}><Lock/> NIGHT {char.day_index + index + 1}</div>)}</div></>; }

function Shop({ items, inventory, char, buy }:{ items:Item[]; inventory:Inventory[]; char:Character; buy:(id:number) => void }) { return <><section className="section-heading"><p className="kicker">FIELD KIT / {char.gold} GOLD AVAILABLE</p><h1>Carry the <em>evidence.</em></h1><p>Small things can be the difference between being remembered and becoming another file on the shelf.</p></section><div className="shop-grid">{items.map((item, index) => { const owned = inventory.some(entry => entry.shop_item_id === item.id); return <article className="item" key={item.id}><div className={'item-art art-'+index}><ShoppingBag/><span>#{String(index + 1).padStart(2, '0')}</span></div><p className="kicker">COSMETIC RELIC</p><h2>{item.name}</h2><p>{item.description}</p><div className="item-bottom"><b>{item.cost} <small>GOLD</small></b><button className="primary" disabled={owned || char.gold < item.cost} onClick={() => buy(item.id)}>{owned ? 'Owned' : char.gold < item.cost ? 'Need gold' : 'Secure'}</button></div></article>; })}</div></>; }

createRoot(document.getElementById('root')!).render(<App/>);
