import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence, motion} from 'framer-motion';
import {BookOpen, CheckCircle2, CircleDollarSign, CloudRain, Lock, Plus, ShoppingBag, Trash2, UserRound} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000';
type Character={id:number;level:number;xp:number;xp_to_next_level:number;resource_meter:number;gold:number;day_index:number;stats:Record<string,number>};
type Quest={id:number;title:string;category:string;difficulty:string;is_completed:boolean;xp_reward:number;gold_reward:number;resource_reward:number};
type Item={id:number;name:string;cost:number;description:string}; type Inventory={id:number;shop_item_id:number;name:string;description:string};
const token=()=>localStorage.getItem('wayfarer-token');
async function api(path:string, options:RequestInit={}) { const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{}) ,...options.headers}}); if(!r.ok) throw new Error((await r.json().catch(()=>({detail:'The line to the station went quiet.'}))).detail); return r.status===204?null:r.json(); }
const categories=['Gym/Sports/Chores','Coding/Study','Reading/Reflection','Sleep/Health/Self-care']; const difficulties=['Easy','Medium','Hard'];

function Auth({onToken}:{onToken:()=>void}){const [signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api(`/auth/${signup?'signup':'login'}`,{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('wayfarer-token',r.access_token);onToken()}catch(e){setError((e as Error).message)}finally{setBusy(false)}} return <main className="arrival"><CloudRain size={52}/><p className="eyebrow">WAYFARER / CASE FILE 001</p><h1>Welcome to the rain.</h1><p>The town has been waiting for its Chief.</p><form onSubmit={submit} className="auth card"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy}>{busy?'Checking the files…':signup?'Arrive in town':'Enter the station'}</button><button type="button" className="link" onClick={()=>setSignup(!signup)}>{signup?'Already recorded? Sign in':'New here? Record your arrival'}</button></form></main>}

function Bar({name,value,max,color='amber'}:{name:string;value:number;max:number;color?:string}){return <div className="bar"><span>{name}</span><div><i className={color} style={{width:`${Math.min(100,value/max*100)}%`}}/></div><b>{value}{max!==100&&` / ${max}`}</b></div>}
function App(){const [ready,setReady]=useState(!!token()),[char,setChar]=useState<Character|null>(null),[quests,setQuests]=useState<Quest[]>([]),[items,setItems]=useState<Item[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[screen,setScreen]=useState<'town'|'quests'|'story'|'shop'>('town'),[story,setStory]=useState<any>(null),[meta,setMeta]=useState({demo_mode:false}),[toast,setToast]=useState(''),[loading,setLoading]=useState(true); const say=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),3500)};
 const load=async()=>{try{const [c,q,i,inv,m]=await Promise.all([api('/character/me'),api('/quests'),api('/shop/items'),api('/inventory/me'),api('/meta')]);setChar(c);setQuests(q);setItems(i);setInventory(inv);setMeta(m)}catch(e){say((e as Error).message);if((e as Error).message.includes('token')){localStorage.removeItem('wayfarer-token');setReady(false)}}finally{setLoading(false)}}; useEffect(()=>{if(ready)load()},[ready]); useEffect(()=>{if(ready&&screen==='story'&&char) api(`/story/day/${char.day_index}`).then(setStory).catch(e=>say(e.message))},[screen,char?.day_index]);
 if(!ready)return <Auth onToken={()=>{setReady(true);setLoading(true)}}/>; if(loading||!char)return <main className="skeleton">The station lights are warming up…</main>;
 const completed=quests.filter(q=>q.is_completed).length; async function complete(q:Quest){setQuests(x=>x.map(v=>v.id===q.id?{...v,is_completed:true}:v));try{const r=await api(`/quests/${q.id}/complete`,{method:'PATCH'});setChar(r.character);setQuests(x=>x.map(v=>v.id===q.id?r.quest:v));say(`Case closed. +${q.xp_reward} XP, +${q.gold_reward} gold.`)}catch(e){setQuests(x=>x.map(v=>v.id===q.id?q:v));say((e as Error).message)}}
 async function advance(){try{const r=await api('/dev/advance-day',{method:'POST'});setChar(r.character);say(r.advanced?'The town sleeps. A new file opens.':'Dawn has already come.')}catch(e){say((e as Error).message)}}
 return <main><div className="rain"/><header><div className="brand"><CloudRain/> WAYFARER</div><nav aria-label="Primary">{[['town','Town'],['quests','Quest Board'],['story','Case Files'],['shop','Locker']].map(([k,n])=><button className={screen===k?'active':''} onClick={()=>setScreen(k as any)} key={k}>{n}</button>)}</nav><button className="link signout" onClick={()=>{localStorage.removeItem('wayfarer-token');setReady(false)}}>Leave</button></header><section className="layout"><aside className="profile card"><UserRound size={40}/><h2>Chief Rook</h2><p>Level {char.level} · Night {char.day_index}</p><Bar name="XP" value={char.xp} max={char.xp_to_next_level}/><Bar name="Clarity" value={char.resource_meter} max={100} color="teal"/><div className="gold"><CircleDollarSign/> {char.gold} gold</div>{Object.entries(char.stats).map(([k,v])=><Bar key={k} name={k} value={v} max={100}/>)}</aside><section className="content"><AnimatePresence mode="wait"><motion.div key={screen} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}}>{screen==='town'&&<Town char={char} completed={completed}/>} {screen==='quests'&&<Board quests={quests} onComplete={complete} reload={load} say={say}/>} {screen==='story'&&<Story story={story} char={char}/>} {screen==='shop'&&<Shop items={items} inventory={inventory} char={char} buy={async(id)=>{try{const r=await api(`/shop/purchase/${id}`,{method:'POST'});setChar(r.character);setInventory(r.inventory);say('Relic secured in the evidence locker.')}catch(e){say((e as Error).message)}}}/>}</motion.div></AnimatePresence></section></section>{meta.demo_mode&&<button className="sleep" onClick={advance}>Sleep · advance night →</button>}<AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="toast" role="status">{toast}</motion.div>}</AnimatePresence></main>}
function Town({char,completed}:{char:Character;completed:number}){return <><p className="eyebrow">THE STATION / NIGHT {char.day_index}</p><h1>The town keeps its secrets.</h1><div className="hero card"><BookOpen/><div><h2>Today's investigation</h2><p>{completed} cases resolved today. The next fragment appears after {Math.max(0,2-(completed%2||2))} more.</p><p className="muted">Follow the rain. Each completed case returns a piece of what was taken.</p></div></div></>}
function Board({quests,onComplete,reload,say}:{quests:Quest[];onComplete:(q:Quest)=>void;reload:()=>void;say:(s:string)=>void}){const [title,setTitle]=useState(''),[category,setCategory]=useState(categories[0]),[difficulty,setDifficulty]=useState('Easy');async function add(e:React.FormEvent){e.preventDefault();try{await api('/quests',{method:'POST',body:JSON.stringify({title,category,difficulty})});setTitle('');reload()}catch(e){say((e as Error).message)}} return <><p className="eyebrow">THE QUEST BOARD</p><h1>Make the next move.</h1><form className="questform card" onSubmit={add}><input placeholder="What needs doing?" value={title} onChange={e=>setTitle(e.target.value)} required/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option>{x}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{difficulties.map(x=><option>{x}</option>)}</select><button><Plus/> Add case</button></form><div className="questlist">{quests.length===0?<div className="card empty">No open cases. Start small; the town is listening.</div>:quests.map(q=><div className={'quest card '+(q.is_completed?'done':'')} key={q.id}><button aria-label={'Complete '+q.title} disabled={q.is_completed} onClick={()=>onComplete(q)}><CheckCircle2/></button><div><h3>{q.title}</h3><span>{q.category}</span> <span>{q.difficulty}</span></div><b>+{q.xp_reward} XP · +{q.gold_reward}g</b><button className="icon" onClick={async()=>{await api(`/quests/${q.id}`,{method:'DELETE'});reload()}} aria-label={'Delete '+q.title}><Trash2/></button></div>)}</div></>}
function Story({story,char}:{story:any;char:Character}){if(!story)return <div className="skeleton">Opening the case file…</div>;return <><p className="eyebrow">CASE FILE / NIGHT {char.day_index}</p><h1>{story.title}</h1><p className="setup">{story.setup}</p>{story.fragments?.map((f:any)=><article className={'fragment card '+(f.variant==='hard'?'hard':'')} key={f.index}>{f.text}</article>)}{story.reveal&&<article className={'reveal card '+(story.reveal.variant==='hard'?'hard':'')}><p className="eyebrow">END-OF-NIGHT REVELATION</p>{story.reveal.text}</article>}{story.finale&&<article className="reveal card">{story.finale}</article>} {story.fragments?.length===0&&<div className="card empty"><Lock/> Complete cases to retrieve this night's evidence.</div>}<div className="future">{Array.from({length:7-char.day_index},(_,i)=><div key={i}><Lock/> Night {char.day_index+i+1}</div>)}</div></>}
function Shop({items,inventory,char,buy}:{items:Item[];inventory:Inventory[];char:Character;buy:(id:number)=>void}){return <><p className="eyebrow">EVIDENCE LOCKER</p><h1>Things worth carrying.</h1><div className="shop">{items.map(i=>{const owned=inventory.some(x=>x.shop_item_id===i.id);return <div className="card item" key={i.id}><ShoppingBag/><h2>{i.name}</h2><p>{i.description}</p><b>{i.cost} gold</b><button disabled={owned||char.gold<i.cost} onClick={()=>buy(i.id)}>{owned?'Owned':char.gold<i.cost?'Need more gold':'Secure relic'}</button></div>})}</div></>}
createRoot(document.getElementById('root')!).render(<App/>);
